// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QQOPOOOVOPO'#CcOOOO'#Ca'#CaQQOPOOO[OQO,58}OOOO-E6_-E6_OaOPO1G.iOfOSO7+$TOkOPO<<GoOOOOAN=ZAN=Z",
  stateData: "p~OQPO~OWSO~ORUO~OXVO~OSWO~OYXO~O",
  goto: "cWPPPPPXP_QRORTRTQOR",
  nodeNames: "⚠ HeaderList Type Name Value",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "5^VR_OY!QYZ#tZp!Qpq$Xq![!Q![!]&_!]#T!Q#T#U'Z#U#Y!Q#Y#Z.i#Z;'S!Q;'S;=`#n<%l~!Q~O!Q~~5XU!XVRQSSOY!QYZ!nZ![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QQ!sSRQO![!n!];'S!n;'S;=`#P<%lO!nQ#SP;=`<%l!nS#[SSSOY#VZ;'S#V;'S;=`#h<%lO#VS#kP;=`<%l#VU#qP;=`<%l!QR#{SRQYPO![!n!];'S!n;'S;=`#P<%lO!nV$`XRQSSOY!QYZ!nZ}!Q}!O${!O![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QV%SXRQSSOY!QYZ!nZp!Qpq%oq![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QV%xVWPRQSSOY!QYZ!nZ![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QT&dUSSOY#VZp#Vpq&vq;'S#V;'S;=`#h<%lO#VT&}SXPSSOY#VZ;'S#V;'S;=`#h<%lO#VV'bXRQSSOY!QYZ!nZ![!Q![!]#V!]#g!Q#g#h'}#h;'S!Q;'S;=`#n<%lO!QV(UXRQSSOY!QYZ!nZ![!Q![!]#V!]#c!Q#c#d(q#d;'S!Q;'S;=`#n<%lO!QV(xXRQSSOY!QYZ!nZ![!Q![!]#V!]#f!Q#f#g)e#g;'S!Q;'S;=`#n<%lO!QV)lXRQSSOY!QYZ!nZ![!Q![!]#V!]#]!Q#]#^*X#^;'S!Q;'S;=`#n<%lO!QV*`XRQSSOY!QYZ!nZ![!Q![!]#V!]#Z!Q#Z#[*{#[;'S!Q;'S;=`#n<%lO!QV+SXRQSSOY!QYZ!nZ![!Q![!]#V!]#]!Q#]#^+o#^;'S!Q;'S;=`#n<%lO!QV+vXRQSSOY!QYZ!nZ![!Q![!]#V!]#b!Q#b#c,c#c;'S!Q;'S;=`#n<%lO!QV,jXRQSSOY!QYZ!nZ![!Q![!]#V!]#T!Q#T#U-V#U;'S!Q;'S;=`#n<%lO!QV-^XRQSSOY!QYZ!nZ![!Q![!]#V!]#`!Q#`#a-y#a;'S!Q;'S;=`#n<%lO!QV.SVRQQPSSOY!QYZ!nZ![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QV.pXRQSSOY!QYZ!nZ![!Q![!]#V!]#]!Q#]#^/]#^;'S!Q;'S;=`#n<%lO!QV/dXRQSSOY!QYZ!nZ![!Q![!]#V!]#b!Q#b#c0P#c;'S!Q;'S;=`#n<%lO!QV0WXRQSSOY!QYZ!nZ![!Q![!]#V!]#T!Q#T#U0s#U;'S!Q;'S;=`#n<%lO!QV0zXRQSSOY!QYZ!nZ![!Q![!]#V!]#`!Q#`#a1g#a;'S!Q;'S;=`#n<%lO!QV1nXRQSSOY!QYZ!nZp!Qpq2Zq![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QV2bXRQSSOY!QYZ!nZp!Qpq2}q![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QV3UXRQSSOY!QYZ!nZp!Qpq3qq![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QV3xXRQSSOY!QYZ!nZp!Qpq4eq![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QV4lXRQSSOY!QYZ!nZp!Qpq-yq![!Q![!]#V!];'S!Q;'S;=`#n<%lO!QP5^OYP",
  tokenizers: [0, 1, 2],
  topRules: {"HeaderList":[0,1]},
  tokenPrec: 0
})
