// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "tOQOPOOOOOO'#Cd'#CdQQOPOOO]OPO'#CbOOOO-E6`-E6`OOOO,58|,58|",
  stateData: "g~OQPORPOSPO~OTTO~OQRSR~",
  goto: "dXPPPPPPYP`QQORSQTROQ",
  nodeNames: "⚠ patternList Domain Host Regex Comment",
  maxTerm: 8,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "'r~R`OY!TZp!Tqs!Tst!ut|!T}!O#^!O!P%h!P!Q!T!Q![#^![!c!T!c!}#^!}#T!T#T#o#^#o;'S!T;'S;=`!o<%lO!T~!YVS~OY!TZp!Tqs!Tt|!T};'S!T;'S;=`!o<%lO!T~!rP;=`<%l!T~!zST~OY!uZ;'S!u;'S;=`#W<%lO!u~#ZP;=`<%l!u~#e_R~S~OY!TZp!Tqs!Tt|!T}!O#^!O!P$d!P!Q!T!Q![#^![!c!T!c!}#^!}#T!T#T#o#^#o;'S!T;'S;=`!o<%lO!T~$i_S~OY!TZp!Tqs!Tt|!T}!O#^!O!P$d!P!Q!T!Q![#^![!c!T!c!}#^!}#T!T#T#o#^#o;'S!T;'S;=`!o<%lO!T~%o_Q~S~OY!TZp!Tqs!Tt|!T}!O%h!O!P&n!P!Q!T!Q![%h![!c!T!c!}%h!}#T!T#T#o%h#o;'S!T;'S;=`!o<%lO!T~&s_S~OY!TZp!Tqs!Tt|!T}!O%h!O!P&n!P!Q!T!Q![%h![!c!T!c!}%h!}#T!T#T#o%h#o;'S!T;'S;=`!o<%lO!T",
  tokenizers: [0],
  topRules: {"patternList":[0,1]},
  tokenPrec: 18
})
