// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pOQOPOOOYOQO'#CfOOOO'#Ce'#CeObOPO'#CeOOOO'#Cc'#CcQQOPOOOgOPO'#CgOOOO,59Q,59QOOOO,59P,59POOOO-E6a-E6aOOOO,59R,59ROrOPO,59ROOOO1G.m1G.m",
  stateData: "!Q~OQQORPO~OSUO[YX~O[WO~OTZOUYO[ZX~OU[O[Za~OQRTUT~",
  goto: "n[PPPPPPP]PcgkQTORXTTSOTTROTRVP",
  nodeNames: "⚠ patternList HeaderLine Scheme Host Path Args",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "-]~R_OY!QYZ'dZs!Qst!ytx!Qxy'iy!P!Q!P!Q%t!Q!_!Q!_!`'i!`!a!Q!a!b!y!b;'S!Q;'S;=`'^<%lO!QR!ZYSQTPUPOY!QZs!Qst!yt!P!Q!P!Q$}!Q!a!Q!a!b!y!b;'S!Q;'S;=`'^<%lO!QR#QUSQUPOY!yZ!P!y!P!Q#d!Q;'S!y;'S;=`$w<%lO!yP#iUUPOY#{Z!P#{!P!Q$d!Q;'S#{;'S;=`$^<%lO#{P$QSUPOY#{Z;'S#{;'S;=`$^<%lO#{P$aP;=`<%l#{P$kSRPUPOY#{Z;'S#{;'S;=`$^<%lO#{R$zP;=`<%l!yP%UYTPUPOY%tZs%tst#{t!P%t!P!Q&k!Q!a%t!a!b#{!b;'S%t;'S;=`&e<%lO%tP%{WTPUPOY%tZs%tst#{t!a%t!a!b#{!b;'S%t;'S;=`&e<%lO%tP&hP;=`<%l%tP&tWRPTPUPOY%tZs%tst#{t!a%t!a!b#{!b;'S%t;'S;=`&e<%lO%tR'aP;=`<%l!Q~'iO[~R'tYSQQPTPUPOY'iZs'ist(dt!P'i!P!Q*p!Q!a'i!a!b(d!b;'S'i;'S;=`-V<%lO'iR(mUSQQPUPOY(dZ!P(d!P!Q)P!Q;'S(d;'S;=`*j<%lO(dP)WUQPUPOY)jZ!P)j!P!Q*T!Q;'S)j;'S;=`)}<%lO)jP)qSQPUPOY)jZ;'S)j;'S;=`)}<%lO)jP*QP;=`<%l)jP*^SQPRPUPOY)jZ;'S)j;'S;=`)}<%lO)jR*mP;=`<%l(dP*yYQPTPUPOY+iZs+ist)jt!P+i!P!Q,b!Q!a+i!a!b)j!b;'S+i;'S;=`,[<%lO+iP+rWQPTPUPOY+iZs+ist)jt!a+i!a!b)j!b;'S+i;'S;=`,[<%lO+iP,_P;=`<%l+iP,mWQPRPTPUPOY+iZs+ist)jt!a+i!a!b)j!b;'S+i;'S;=`,[<%lO+iR-YP;=`<%l'i",
  tokenizers: [0, 1],
  topRules: {"patternList":[0,1]},
  tokenPrec: 42
})
